### PR TITLE
Python3 support with further test

### PR DESCRIPTION
**Pull request by robertwenquan**
fixed the UnicodeDecodeError: 'ascii' codec can't decode error

[Review on Reviewable](https://reviewable.io/reviews/clarifai/clarifai_py/11)

### CODE REVIEW

**Comment by adamberenzweig** [comment]
Is this one obsolete now, or should I still review?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clarifai/clarifai_py/11)

**Comment by robertwenquan** [comment]
Let me merge with master and check again as we had some changes in the last week. I think we may need more change on this branch. Will let u know. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clarifai/clarifai_py/11)

**Comment by robertwenquan** [comment]
+@adamberenzweig The Python3 support is almost complete. Added more tests and verified on both Python 2.7 and 3.4

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clarifai/clarifai_py/11)

**Comment by zeiler** [comment]
@vinayan3 @adamberenzweig please review so we can merge and make it live!

**Comment by vinayan3** [comment]
LGTM.

**Pull request merged**
